#!/usr/bin/env bash
# script that install Nginx web server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://github.com/ellarepo;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
