#!/usr/bin/env bash
#Bash script that creates the file /var/run/myscript.pid containing its PID
myscript="/var/run/myscript.pid"
echo $$ > $myscript
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT 
trap 'rm -rf /var/run/myscript.pid; exit 0' SIGQUIT 

while true
do
    echo "To infinity and beyond"
done
