#!/usr/bin/env bash
#Bash script that creates the file /var/run/myscript.pid containing its PID
mypid="/var/run/my_process.pid"
my_process="./manage_my_process"

start(){
    $my_process &
    echo $! > "$mypid"
}
stop(){
    if [ -f $mypid ]
    then
        kill "$(cat "$mypid")"
        rm -f $mypid
    fi
}
case "$1" in
    start)
        start
        echo "manage_my_process started"
        ;;
    stop)
        stop
        echo "manage_my_process stopped"
        ;;
    restart)
        stop
        start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
exit 0
